variable "avail_zone" {}
variable "env_prefix" {}
variable "vpc_id" {}
variable "public_key_location" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "my_ip" {}
variable "image_name" {}
variable "user_data_location" {}